export type IconThemeData = keyof typeof iconsData;

export const iconsData = {
  nature: {
    label: 'Natureza',
    verseIcon: 'nature/verse.png',
    prevIcons: ['nature/🎂.png', 'nature/⏸.png'],
    icons: [
      'nature/1.png',
      'nature/2.png',
      'nature/3.png',
      'nature/5.png',
      'nature/8.png',
      'nature/13.png',
      'nature/20.png',
      'nature/40.png',
      'nature/100.png',
      'nature/∞.png',
    ],
    latterIcons: ['nature/🐉.png', 'nature/💈.png'],
  },
  simple: {
    label: 'Simples',
    verseIcon: 'simple/verse.png',
    prevIcons: [],
    icons: [
      'simple/1.png',
      'simple/2.png',
      'simple/3.png',
      'simple/5.png',
      'simple/8.png',
      'simple/13.png',
      'simple/21.png',
      'simple/34.png',
      'simple/55.png',
      'simple/89.png',
    ],
    latterIcons: [],
  },
  cheap: {
    label: 'Baralho',
    verseIcon: 'cheap/verse.png',
    prevIcons: ['cheap/j-clubs.png', 'cheap/q-hearts.png', 'cheap/k-diamonds.png'],
    icons: [
      'cheap/1.png',
      'cheap/2.png',
      'cheap/3.png',
      'cheap/5.png',
      'cheap/8.png',
      'cheap/13.png',
      'cheap/21.png',
      'cheap/joker.png',
    ],
    latterIcons: ['cheap/j-diamonds.png', 'cheap/q-spades.png', 'cheap/k-clubs.png'],
  },
  deadline: {
    label: 'Deadline',
    verseIcon: 'deadline/verse.png',
    prevIcons: [],
    icons: [
      'deadline/0.png',
      'deadline/1.png',
      'deadline/2.png',
      'deadline/3.png',
      'deadline/5.png',
      'deadline/8.png',
      'deadline/13.png',
      'deadline/21.png',
      'deadline/34.png',
      'deadline/55.png',
      'deadline/89.png',
      'deadline/144.png',
      'deadline/233.png',
      'deadline/377.png',
      'deadline/610.png',
      'deadline/987.png',
      'deadline/∞.png'
    ],
    latterIcons: [
      'deadline/☕.png',
      'deadline/🏓.png'
    ],
  },
};
